### ISSUE TITLE
Add PayForMessage Tx type

### ISSUE THREAD

**Issue by liamsi** [lazyledger/cosmos-sdk#4]
After #2 and #1, we should start implementing the LazyLedger specific transactions. 

The relevant part of the spec: https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#signedtransactiondatapayformessage

**Comment by marbar3778** [comment]
This has some overlap with fee grant module: https://github.com/cosmos/cosmos-sdk/pull/5768/files. It would need to have some modifications but it's a good starting point.

**Comment by liamsi** [comment]
@marbar3778 this looks interesting but it seems relatively far away from the [SignedTransactionDataPayForMessage](https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#signedtransactiondatapayformessage). Although it plays into a discussion we had internally: namely, that ideally, one should not need to have LL tokens or to "maintain a wallet with sufficient fees". The PayForMessage Tx type still seems quite different but maybe I'm missing sth.

**Comment by liamsi** [comment]
The type will be added in the lazyledger-app / module instead of the SDK fork directly. See https://github.com/lazyledger/lazyledger-app/pull/21 and https://github.com/lazyledger/lazyledger-app/issues/22
